name: Continuous Deployment

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  publish-shipengine-gem:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: ruby
          package-name: shipengine_rb
          bump-minor-pre-major: true
          version-file: lib/shipengine_rb/version.rb

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        if: ${{ steps.release.outputs.release_created }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
        if: ${{ steps.release.outputs.release_created }}

      - name: Publish ShipEngine Gem
        if: ${{ steps.release.outputs.release_created }}
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials

          cat <<EOF >$HOME/.gem/credentials
          ---
          :rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}
          EOF

          rake release
